### ISSUE TITLE
Error occurred in Python: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by Desperado17** [ChaChaNop-Slide/ptrfind#1]
I tried this on an Aarch64 Gdb 11.1 with coredump:

(gdb) ptrfind libc --from image
Python Exception <class 'AttributeError'>: 'NoneType' object has no attribute 'name'
Error occurred in Python: 'NoneType' object has no attribute 'name'

Any suggestions?

**Comment by kammt** [comment]
Hi there!

to make it easier to find the root cause of this error, could you post the output of the following two gdb-commands while debugging your coredump?

1. `i proc m`
2. `py PtrFind().invoke("libc --from image", True)`

The second command runs `ptrfind` inside gdb's Python shell, which prints the entire stack trace in case of an error.

Thanks!

**Comment by Desperado17** [comment]
i proc m

This seems to dump the memory mappings a la proc/pid/maps:

...
        0x7eff580000       0x7eff600000    0x80000 0x7eff580000 /dev/mali0
        0x7eff600000       0x7eff88b000   0x28b000 0x7eff600000 /dev/mali0
        0x7eff88d000       0x7eff895000     0x8000 0x7eff88d000 /dev/mali0
        0x7eff895000       0x7eff89d000     0x8000 0x7eff895000 /dev/mali0
        0x7eff89d000       0x7eff8a5000     0x8000 0x7eff89d000 /dev/mali0
...

Also shared objects.

(gdb) source /home/user/Documents/ptrfind/ptrfind/ptrfind.py 
(gdb) py PtrFind().invoke("libc --from image", True)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/Documents/ptrfind/ptrfind/ptrfind.py", line 133, in invoke
    self.create_proc_map()
  File "/home/user/Documents/ptrfind/ptrfind/ptrfind.py", line 621, in create_proc_map
    if current_objfile.name == "":
AttributeError: 'NoneType' object has no attribute 'name'
Error while executing Python code.

**Comment by Desperado17** [comment]
My aarch64 gdb shows no permissions column in the i proc m output. The binary name is in column 4 instead of 5.

**Comment by Desperado17** [comment]
Also, the adress lines start at index :3 not :4 of the output:

(gdb) i proc m
Mapped address spaces:

          Start Addr           End Addr       Size     Offset objfile
        0x557ead9000       0x5582dee000  0x4315000        0x0 /usr/bin/myproc
        0x5582dfe000       0x5582f0a000   0x10c000  0x4315000 /usr/bin/myproc
        0x5582f0a000       0x5582f24000    0x1a000  0x4421000 /usr/bin/myproc


    for line in mappings_output:
      PtrFind.print_error(f"Line to parse: {line}")
      
The loop erroneously starts with the second line:     
[-] Line to parse:         0x5582dfe000       0x5582f0a000   0x10c000  0x4315000 /usr/bin/myproc

**Comment by Desperado17** [comment]
Another thing: info proc mappings doesn't seem to list stack segments on aarch64.

**Comment by Desperado17** [comment]
I suggest the output of maintenance info sections is more useful for composing all mapped memory regions at least if you don't need the stack etc. markers. The full i proc m output with all sections may not be present on post mortem coredumps.

Or maybe add an option so users can enumerate these regions too.
